[colors.bright]
black = "#424242"
blue = "#8DA3B9"
cyan = "#8AA6A2"
green = "#8C977D"
magenta = "#A988B0"
red = "#B66467"
white = "#E8E3E3"
yellow = "#D9BC8C"

[colors.normal]
black = "#151515"
blue = "#8DA3B9"
cyan = "#8AA6A2"
green = "#8C977D"
magenta = "#A988B0"
red = "#B66467"
white = "#E8E3E3"
yellow = "#D9BC8C"

[colors.primary]
background = "#151515"
foreground = "#E8E3E3"

[cursor]
style = "beam"
thickness = 0.2
unfocused_hollow = false

[font]
size = 9

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[shell]
program = "/bin/bash"

[window]
opacity = 0.9

[window.padding]
x = 20
y = 10
