shell = "/bin/zsh"

[font.normal]
family="Firacode Nerd Font Mono"
style="SemiBold"

[font]
offset.y = 4
size = 8

[window]
padding = {x = 10, y = 5}
dimensions = {columns = 209, lines = 44}

[cursor]
style = {shape = "beam", blinking = "off"}
thickness = 0.6

# Moonfly theme #
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#080808"
foreground = "#b2b2b2"
bright_foreground = "#eeeeee"

[colors.cursor]
text = "#080808"
cursor = "#9e9e9e"

[colors.selection]
text = "#080808"
background = "#b2ceee"

[colors.normal]
black = "#323437"
red = "#ff5454"
green = "#8cc85f"
yellow = "#e3c78a"
blue = "#80a0ff"
magenta = "#d183e8"
cyan = "#79dac8"
white = "#c6c6c6"

[colors.bright]
black = "#949494"
red = "#ff5189"
green = "#36c692"
yellow = "#bfbf97"
blue = "#74b2ff"
magenta = "#ae81ff"
cyan = "#85dc85"
white = "#e4e4e4"
