alias p = sudo pacman
alias cowsay = clear; cowsay
alias gpp = g++
alias py = python3 -u
alias cat = bat
alias loc = plocate
alias nv = nvim
alias nf = nvim (fzf)
alias lg = lazygit
alias internet = /bin/watch -n 0.5 lsof -i
alias tlauncher = sudo java -jar /home/darth/the-duat/Applications/Tlauncher/TLauncher.jar
alias deepseek = ollama run deepseek-r1:1.5b
alias uv = uvx --python 3.11 open-webui@latest serve
alias k = sudo systemctl restart kmonad
alias wdk = sudo systemctl restart wdkmonad
