#! /bin/sh

#chosen=$(printf "Log Out\nShutdown\nReboot\nSuspend\nLock" | rofi --config $HOME/.config/tofi/powermenu-config)
chosen=$(printf "Log Out\nShutdown\nReboot\nSuspend\nLock" | rofi -dmenu -i)

case "$chosen" in
	"Lock") lockscreen ;;
	"Suspend") systemctl suspend-then-hibernate ;;
	"Reboot") reboot ;;
	"Shutdown") shutdown now ;;
	"Log Out") hyprctl dispatch exit ;;
	*) exit 1 ;;
esac
